language: c
sudo: required
dist: trusty

branches:
  except:
  - gh-pages

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libtorque2-dev
  - sudo apt-get install -y python-pip python-virtualenv python-dev

notifications:
  email:
    recipients:
      - akohlmey@gmail.com
    on_successs: change
    on_failure: always
  slack: templehpc:DkATySl5C1CNkbgOb5yE4zsq

compiler:
  - gcc
  - clang

script:
  - ./configure --with-pbs CFLAGS="-Wall -O2 -g -fno-strict-aliasing"
  - make
  - make test

after_success:
  - if [ "$CC" = gcc ] ; then ./tools/generateDocsAndDeploy.sh ; fi
